# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: catalog.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcatalog.proto\x12\x07\x63\x61talog\"0\n\nBuyRequest\x12\x10\n\x08ItemName\x18\x01 \x01(\t\x12\x10\n\x08Quantity\x18\x02 \x01(\x05\" \n\x0cQueryRequest\x12\x10\n\x08ItemName\x18\x01 \x01(\t\"\x1f\n\x0b\x42uyResponse\x12\x10\n\x08Response\x18\x01 \x01(\x05\":\n\rQueryResponse\x12\x0c\n\x04\x43ost\x18\x01 \x01(\x01\x12\r\n\x05Stock\x18\x02 \x01(\x05\x12\x0c\n\x04Name\x18\x03 \x01(\t2s\n\x07\x43\x61talog\x12\x36\n\x05Query\x12\x15.catalog.QueryRequest\x1a\x16.catalog.QueryResponse\x12\x30\n\x03\x42uy\x12\x13.catalog.BuyRequest\x1a\x14.catalog.BuyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'catalog_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_BUYREQUEST']._serialized_start=26
  _globals['_BUYREQUEST']._serialized_end=74
  _globals['_QUERYREQUEST']._serialized_start=76
  _globals['_QUERYREQUEST']._serialized_end=108
  _globals['_BUYRESPONSE']._serialized_start=110
  _globals['_BUYRESPONSE']._serialized_end=141
  _globals['_QUERYRESPONSE']._serialized_start=143
  _globals['_QUERYRESPONSE']._serialized_end=201
  _globals['_CATALOG']._serialized_start=203
  _globals['_CATALOG']._serialized_end=318
# @@protoc_insertion_point(module_scope)
